name: Build, self (amd64, dind), buildx
run-name: Build, self (amd64, dind), buildx

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: set-linux-amd64-dind
    permissions: write-all
    timeout-minutes: 120

    outputs:
      digest: ${{ steps.build-push.outputs.digest }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        uses: docker/metadata-action@v5
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        id: build-push
        with:
         push: true
         context: .
         tags: ${{ steps.metadata.outputs.tags }}_self-buildx
         labels: ${{ steps.metadata.outputs.labels }}

      - name: Print the Image Digest
        run: echo "The image digest is ${{ steps.build-push.outputs.digest }}"
